## rSpawn Config File ##
# don't touch this. this ensures updates to config file are installed
version: 1


## Options ##
# players will not spawn in these biomes, full list of biomes available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
disabled-biomes:
  - COLD_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_OCEAN
  - DEEP_WARM_OCEAN
  - LUKEWARM_OCEAN
  - OCEAN
  - WARM_OCEAN


## Range ##
# the radius of the square of allowed spawns from X = 0 and Z = 0
radius:
  x: 4000
  z: 4000